//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS_EmailReminder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DocumentControlEntities : DbContext
    {
        public DocumentControlEntities()
            : base("name=DocumentControlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TD_Document> TD_Document { get; set; }
        public DbSet<TD_Transaction> TD_Transaction { get; set; }
        public DbSet<V_Max_Transaction> V_Max_Transaction { get; set; }
        public DbSet<V_Transaction> V_Transaction { get; set; }
        public DbSet<TM_Action> TM_Action { get; set; }
        public DbSet<TM_DocType> TM_DocType { get; set; }
        public DbSet<TM_GroupCode> TM_GroupCode { get; set; }
        public DbSet<TM_Level> TM_Level { get; set; }
        public DbSet<TM_Operation> TM_Operation { get; set; }
        public DbSet<TM_Status> TM_Status { get; set; }
        public DbSet<TM_User> TM_User { get; set; }
        public DbSet<TM_UserType> TM_UserType { get; set; }
        public DbSet<V_DistributionDoc> V_DistributionDoc { get; set; }
    }
}
