//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS_EmailReminder
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_Document
    {
        public TD_Document()
        {
            this.TD_Transaction = new HashSet<TD_Transaction>();
        }
    
        public string doc_type_short { get; set; }
        public string group_code { get; set; }
        public int run_no { get; set; }
        public byte rev_no { get; set; }
        public string doc_name { get; set; }
        public System.DateTime eff_date { get; set; }
        public string attach_file { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> expect_cancel_date { get; set; }
        public Nullable<System.DateTime> check_date { get; set; }
        public string reference { get; set; }
    
        public virtual ICollection<TD_Transaction> TD_Transaction { get; set; }
        public virtual TM_DocType TM_DocType { get; set; }
        public virtual TM_GroupCode TM_GroupCode { get; set; }
    }
}
