//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISODocument.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_ReqCopy
    {
        public TD_ReqCopy()
        {
            this.TD_TranCopy = new HashSet<TD_TranCopy>();
        }
    
        public int req_id { get; set; }
        public string doc_type_short { get; set; }
        public string group_code { get; set; }
        public int run_no { get; set; }
        public byte rev_no { get; set; }
        public int qty { get; set; }
        public string type { get; set; }
        public byte paper_id { get; set; }
        public string reason { get; set; }
    
        public virtual TM_Paper TM_Paper { get; set; }
        public virtual ICollection<TD_TranCopy> TD_TranCopy { get; set; }
        public virtual TD_Document TD_Document { get; set; }
    }
}
