//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISODocument.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Operation
    {
        public TM_Operation()
        {
            this.TD_Transaction = new HashSet<TD_Transaction>();
        }
    
        public byte operation_id { get; set; }
        public string operation_name { get; set; }
        public string update_by { get; set; }
        public System.DateTime update_dt { get; set; }
    
        public virtual ICollection<TD_Transaction> TD_Transaction { get; set; }
    }
}
