//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISODocument.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Sum_CopyDoc
    {
        public string doc_no { get; set; }
        public byte rev_no { get; set; }
        public string doc_type_short { get; set; }
        public string group_code { get; set; }
        public int run_no { get; set; }
        public int group_id { get; set; }
        public Nullable<int> round { get; set; }
        public Nullable<int> qty { get; set; }
    }
}
