//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISODocument.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TranCopy
    {
        public string doc_no { get; set; }
        public string doc_type_short { get; set; }
        public string group_code { get; set; }
        public int run_no { get; set; }
        public byte rev_no { get; set; }
        public int qty { get; set; }
        public string type { get; set; }
        public string reason { get; set; }
        public byte paper_id { get; set; }
        public string paper_name { get; set; }
        public bool active { get; set; }
        public System.DateTime act_dt { get; set; }
        public string actor { get; set; }
        public Nullable<byte> action_id { get; set; }
        public int org_id { get; set; }
        public byte lv_id { get; set; }
        public byte status_id { get; set; }
        public int req_id { get; set; }
        public string statusname { get; set; }
        public string lv_name { get; set; }
        public string status_name { get; set; }
        public string action_name { get; set; }
    }
}
