//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISODocument.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Transaction
    {
        public string doc_no { get; set; }
        public string doc_type_short { get; set; }
        public string group_code { get; set; }
        public int run_no { get; set; }
        public byte rev_no { get; set; }
        public byte sub_rev { get; set; }
        public byte status_id { get; set; }
        public byte lv_id { get; set; }
        public int org_id { get; set; }
        public byte operation_id { get; set; }
        public Nullable<byte> action_id { get; set; }
        public string actor { get; set; }
        public Nullable<System.DateTime> act_dt { get; set; }
        public string comment { get; set; }
        public bool active { get; set; }
        public string doc_name { get; set; }
        public System.DateTime eff_date { get; set; }
        public string attach_file { get; set; }
        public string remark { get; set; }
        public string statusname { get; set; }
        public string operation_name { get; set; }
        public string lv_name { get; set; }
        public string status_name { get; set; }
        public string doc_type_full { get; set; }
        public byte doc_lv { get; set; }
        public byte review_year { get; set; }
        public bool copy_flag { get; set; }
        public Nullable<System.DateTime> expect_cancel_date { get; set; }
        public string group_name { get; set; }
    }
}
