//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS_EmailControlledDoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_DocCopy
    {
        public string req_no { get; set; }
        public string doc_type_short { get; set; }
        public string group_code { get; set; }
        public int run_no { get; set; }
        public byte rev_no { get; set; }
        public byte paper_id { get; set; }
        public byte type_id { get; set; }
        public int qty { get; set; }
        public System.DateTime print_dt { get; set; }
        public string receive_by { get; set; }
        public Nullable<System.DateTime> receive_dt { get; set; }
    
        public virtual TD_ReqCopy TD_ReqCopy { get; set; }
        public virtual TM_Paper TM_Paper { get; set; }
    }
}
