//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS_EmailControlledDoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_DistributionList
    {
        public string doc_type_short { get; set; }
        public string group_code { get; set; }
        public int run_no { get; set; }
        public byte rev_no { get; set; }
        public int group_id { get; set; }
    
        public virtual TD_Document TD_Document { get; set; }
    }
}
