//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS_EmailControlledDoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_Questionair
    {
        public string emp_code { get; set; }
        public System.DateTime act_dt { get; set; }
        public byte u1 { get; set; }
        public byte u2 { get; set; }
        public byte u3 { get; set; }
        public byte u4 { get; set; }
        public byte u5 { get; set; }
        public byte u6 { get; set; }
        public byte o1 { get; set; }
        public byte o2 { get; set; }
        public byte o3 { get; set; }
        public byte o4 { get; set; }
        public byte o5 { get; set; }
        public byte o6 { get; set; }
        public byte o7 { get; set; }
        public byte o8 { get; set; }
        public byte o9 { get; set; }
        public byte o10 { get; set; }
        public byte o11 { get; set; }
        public byte o12 { get; set; }
        public byte o13 { get; set; }
        public byte o14 { get; set; }
        public byte o15 { get; set; }
        public byte o16 { get; set; }
        public byte o17 { get; set; }
        public byte o18 { get; set; }
        public byte n1 { get; set; }
        public byte n2 { get; set; }
        public byte n3 { get; set; }
        public byte n4 { get; set; }
        public byte n5 { get; set; }
        public byte n6 { get; set; }
        public byte n7 { get; set; }
        public byte n8 { get; set; }
        public byte n9 { get; set; }
        public byte n10 { get; set; }
        public byte n11 { get; set; }
        public byte n12 { get; set; }
        public byte n13 { get; set; }
        public byte n14 { get; set; }
        public byte n15 { get; set; }
        public byte n16 { get; set; }
        public byte n17 { get; set; }
        public byte n18 { get; set; }
    }
}
