//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS_EmailControlledDoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_ReqCopy
    {
        public TD_ReqCopy()
        {
            this.TD_DocCopy = new HashSet<TD_DocCopy>();
            this.TD_Transaction_Copy = new HashSet<TD_Transaction_Copy>();
        }
    
        public string req_no { get; set; }
        public string reason { get; set; }
        public string ext { get; set; }
    
        public virtual ICollection<TD_DocCopy> TD_DocCopy { get; set; }
        public virtual ICollection<TD_Transaction_Copy> TD_Transaction_Copy { get; set; }
    }
}
