//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS_EmailControlledDoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_Transaction_Copy
    {
        public string req_no { get; set; }
        public byte sub_rev { get; set; }
        public byte status_id { get; set; }
        public byte lv_id { get; set; }
        public int org_id { get; set; }
        public Nullable<byte> action_id { get; set; }
        public string actor { get; set; }
        public System.DateTime act_dt { get; set; }
        public string comment { get; set; }
        public bool active { get; set; }
    
        public virtual TD_ReqCopy TD_ReqCopy { get; set; }
    }
}
