//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS_EmailControlledDoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Reviewer_Prod
    {
        public int group_id { get; set; }
        public int qc_group { get; set; }
        public int en_group { get; set; }
        public string update_by { get; set; }
        public System.DateTime update_dt { get; set; }
    }
}
