//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS_EmailControlledDoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Max_Transaction
    {
        public string doc_no { get; set; }
        public string doc_type_short { get; set; }
        public string group_code { get; set; }
        public int run_no { get; set; }
        public byte rev_no { get; set; }
        public byte status_id { get; set; }
        public string doc_name { get; set; }
        public System.DateTime eff_date { get; set; }
        public string attach_file { get; set; }
        public string remark { get; set; }
        public byte operation_id { get; set; }
        public byte lv_id { get; set; }
        public int org_id { get; set; }
        public Nullable<System.DateTime> act_dt { get; set; }
        public string reference { get; set; }
        public Nullable<System.DateTime> expect_cancel_date { get; set; }
        public Nullable<System.DateTime> check_date { get; set; }
        public bool active { get; set; }
    }
}
